Spring:
  profiles:
    active: prod
  kafka:
    producer:
      bootstrap-servers: kafka:9092,kafka:9093,kafka:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
